[package]
name = "videostream"
version = "0.1.0"
authors = ["jbfp <jakob@jbfp.dk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.38"
bytes = "1.0"
dirs = "3.0"
flate2 = "1.0"
futures = "0.3.9"
lazy_static = "1.4"
log = "0.4"
open = "1.4"
percent-encoding = "2.1.0"
pretty_env_logger = "0.4"
regex = "1"
reqwest = { version ="0.11.0", features = ["json"] }
rocket = "0.5.0-dev"
rocket_contrib = { version = "0.5.0-dev", default-features = false, features = ["json", "serve"] }
rocket_cors = { version = "0.5.2", default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
test-case = "1.1.0"

[patch.crates-io]
rocket = { git = 'https://github.com/SergioBenitez/Rocket', branch = "master" }
rocket_contrib = { git = 'https://github.com/SergioBenitez/Rocket', branch = "master" }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors.git", branch = "master" }
